export const dataKeyTwo = {
    "properties": [
    {
        "_id": "123123",
        "index": 0,
        "price": "99.000",
        "old_price": "155.000",
        "picture": "https://i.postimg.cc/NfCczVMg/slider-element-2.png",
        "subtitle": "Revo Everyday được phối trộn giữa vị đắng của hạt Robusta và hương thơm...",
        "title": "Combo Revo Đậm Đà",
        "link": "CHI TIẾT",


    },
    {
        "_id": "12341234",
        "index": 1,
        "price": "100.000",
        "old_price": "165.000",
        "picture": "https://i.postimg.cc/V6f6FXjG/slider-element-big-2.png",
        "subtitle": "Honey – trong tên gọi Revo Honey đến từ phương pháp chế biến hạt Arabica...",
        "title": "Combo Revo Everyday",
        "link": "CHI TIẾT",
    },
    {
        "_id": "1234512345",
        "index": 2,
        "price": "139.000",
        "old_price": "250.000",
        "picture": "https://i.postimg.cc/yYgNn1ZH/slider-element-big-3.png",
        "subtitle": "Hàm lượng caffein trong Revo Đậm Đà đủ mạnh để làm bạn tỉnh táo làm việc...",
        "title": "Combo Revo Honey",
        "link": "CHI TIẾT",
    },
    {
        "_id": "123456123456",
        "index": 3,
        "price": "75.000",
        "old_price": "15.000",
        "picture": "https://i.postimg.cc/V6f6FXjG/slider-element-big-2.png",
        "subtitle": "Hàm lượng caffein trong Revo Đậm Đà đủ mạnh để làm bạn tỉnh táo làm việc...",
        "title": "REVO Đậm Đà",
        "link": "CHI TIẾT",
    },
    {
        "_id": "12345671234567",
        "index": 4,
        "price": "70.000",
        "old_price": "15.000",
        "picture": "https://i.postimg.cc/yYgNn1ZH/slider-element-big-3.png",
        "subtitle": "Hàm lượng caffein trong Revo Đậm Đà đủ mạnh để làm bạn tỉnh táo làm việc...",
        "title": "REVO Đậm Đà",
        "link": "CHI TIẾT",
    },
    {
        "_id": "123456712345678",
        "index": 5,
        "price": "70.000",
        "old_price": "15.000",
        "picture": "https://i.postimg.cc/NfCczVMg/slider-element-2.png",
        "subtitle": "Hàm lượng caffein trong Revo Đậm Đà đủ mạnh để làm bạn tỉnh táo làm việc...",
        "title": "REVO Đậm Đà",
        "link": "CHI TIẾT",
    },
    {
        "_id": "1234567123456789",
        "index": 6,
        "price": "70.000",
        "old_price": "15.000",
        "picture": "https://i.postimg.cc/V6f6FXjG/slider-element-big-2.png",
        "subtitle": "Hàm lượng caffein trong Revo Đậm Đà đủ mạnh để làm bạn tỉnh táo làm việc...",
        "title": "REVO Đậm Đà",
        "link": "CHI TIẾT",
    },    
    {
        "_id": "1234567123456789000",
        "index": 7,
        "price": "70.000",
        "old_price": "15.000",
        "picture": "https://i.postimg.cc/NfCczVMg/slider-element-2.png",
        "subtitle": "Hàm lượng caffein trong Revo Đậm Đà đủ mạnh để làm bạn tỉnh táo làm việc...",
        "title": "REVO Đậm Đà",
        "link": "CHI TIẾT",
    },
    {
        "_id": "1234567123456789008",
        "index": 8,
        "price": "70.000",
        "old_price": "15.000",
        "picture": "https://i.postimg.cc/V6f6FXjG/slider-element-big-2.png",
        "subtitle": "Hàm lượng caffein trong Revo Đậm Đà đủ mạnh để làm bạn tỉnh táo làm việc...",
        "title": "REVO Đậm Đà",
        "link": "CHI TIẾT",
    },
    {
        "_id": "1234567123456789007",
        "index": 9,
        "price": "70.000",
        "old_price": "15.000",
        "picture": "https://i.postimg.cc/NfCczVMg/slider-element-2.png",
        "subtitle": "Hàm lượng caffein trong Revo Đậm Đà đủ mạnh để làm bạn tỉnh táo làm việc...",
        "title": "REVO Đậm Đà",
        "link": "CHI TIẾT",
    },
    {
        "_id": "1234567123456789006",
        "index": 10,
        "price": "70.000",
        "old_price": "15.000",
        "picture": "https://i.postimg.cc/V6f6FXjG/slider-element-big-2.png",
        "subtitle": "Hàm lượng caffein trong Revo Đậm Đà đủ mạnh để làm bạn tỉnh táo làm việc...",
        "title": "REVO Đậm Đà",
        "link": "CHI TIẾT",
    },
    {
        "_id": "1234567123456789005",
        "index": 11,
        "price": "70.000",
        "old_price": "15.000",
        "picture": "https://i.postimg.cc/yYgNn1ZH/slider-element-big-3.png",
        "subtitle": "Hàm lượng caffein trong Revo Đậm Đà đủ mạnh để làm bạn tỉnh táo làm việc...",
        "title": "REVO Đậm Đà",
        "link": "CHI TIẾT",
    },
    {
        "_id": "1234567123456789004",
        "index": 12,
        "price": "70.000",
        "old_price": "15.000",
        "picture": "https://i.postimg.cc/V6f6FXjG/slider-element-big-2.png",
        "subtitle": "Hàm lượng caffein trong Revo Đậm Đà đủ mạnh để làm bạn tỉnh táo làm việc...",
        "title": "REVO Đậm Đà",
        "link": "CHI TIẾT",
    },
    {
        "_id": "1234567123456789003",
        "index": 13,
        "price": "70.000",
        "old_price": "15.000",
        "picture": "https://i.postimg.cc/V6f6FXjG/slider-element-big-2.png",
        "subtitle": "Hàm lượng caffein trong Revo Đậm Đà đủ mạnh để làm bạn tỉnh táo làm việc...",
        "title": "REVO Đậm Đà",
        "link": "CHI TIẾT",
    },
    {
        "_id": "1234567123456789002",
        "index": 14,
        "price": "70.000",
        "old_price": "15.000",
        "picture": "https://i.postimg.cc/yYgNn1ZH/slider-element-big-3.png",
        "subtitle": "Hàm lượng caffein trong Revo Đậm Đà đủ mạnh để làm bạn tỉnh táo làm việc...",
        "title": "REVO Đậm Đà",
        "link": "CHI TIẾT",
    },
    {
        "_id": "12345671234567890011",
        "index": 15,
        "price": "70.000",
        "old_price": "15.000",
        "picture": "https://i.postimg.cc/V6f6FXjG/slider-element-big-2.png",
        "subtitle": "Hàm lượng caffein trong Revo Đậm Đà đủ mạnh để làm bạn tỉnh táo làm việc...",
        "title": "REVO Đậm Đà",
        "link": "CHI TIẾT",
    },
    {
        "_id": "123456712345678900111",
        "index": 16,
        "price": "70.000",
        "old_price": "15.000",
        "picture": "https://i.postimg.cc/NfCczVMg/slider-element-2.png",
        "subtitle": "Hàm lượng caffein trong Revo Đậm Đà đủ mạnh để làm bạn tỉnh táo làm việc...",
        "title": "REVO Đậm Đà",
        "link": "CHI TIẾT",
    },
    {
        "_id": "1234567123456789001111",
        "index": 17,
        "price": "70.000",
        "old_price": "15.000",
        "picture": "https://i.postimg.cc/V6f6FXjG/slider-element-big-2.png",
        "subtitle": "Hàm lượng caffein trong Revo Đậm Đà đủ mạnh để làm bạn tỉnh táo làm việc...",
        "title": "REVO Đậm Đà",
        "link": "CHI TIẾT",
    },
    {
        "_id": "12345671234567890011111",
        "index": 18,
        "price": "70.000",
        "old_price": "15.000",
        "picture": "https://i.postimg.cc/yYgNn1ZH/slider-element-big-3.png",
        "subtitle": "Hàm lượng caffein trong Revo Đậm Đà đủ mạnh để làm bạn tỉnh táo làm việc...",
        "title": "REVO Đậm Đà",
        "link": "CHI TIẾT",
    }
    ]
}
