export const dataKey = {
    "properties": [
    {
        "_id": "123",
        "index": 0,
        "price": "99.000",
        "picture": "https://i.postimg.cc/LXG8NSkg/slider-element-1.png",
        "subtitle": "đắng, hậu ngọt, hương hoa ",
        "title": "REVO Morning",
        "link": "CHI TIẾT",

    },
    {
        "_id": "1234",
        "index": 1,
        "price": "85.000",
        "picture": "https://i.postimg.cc/BvFwJfx9/slider-element-2.png",
        "subtitle": "cân bằng, hậu đắng, vị chocolate ",
        "title": "REVO Everyday",
        "link": "CHI TIẾT",
    },
    {
        "_id": "12345",
        "index": 2,
        "price": "139.000",
        "picture": "https://i.postimg.cc/mDRVRzLC/slider-element-3.png",
        "subtitle": "đậm đà, đắng, truyền thống",
        "title": "REVO Origin",
        "link": "CHI TIẾT",
    },
    {
        "_id": "123456",
        "index": 3,
        "price": "75.000",
        "picture": "https://i.postimg.cc/BvFwJfx9/slider-element-2.png",
        "subtitle": "đậm đà, đắng, truyền thống",
        "title": "REVO Đậm Đà",
        "link": "CHI TIẾT",
    },
    {
        "_id": "1234567",
        "index": 4,
        "price": "70.000",
        "picture": "https://i.postimg.cc/LXG8NSkg/slider-element-1.png",
        "subtitle": "hậu ngọt, ít đắng, vị chua dâu",
        "title": "REVO Đậm Đà",
        "link": "CHI TIẾT",
    },
    {
        "_id": "12345671",
        "index": 5,
        "price": "70.000",
        "picture": "https://i.postimg.cc/mDRVRzLC/slider-element-3.png",
        "subtitle": "hậu ngọt, ít đắng, vị chua dâu",
        "title": "REVO Đậm Đà",
        "link": "CHI TIẾT",
    },
    {
        "_id": "12345672",
        "index": 6,
        "price": "70.000",
        "picture": "https://i.postimg.cc/LXG8NSkg/slider-element-1.png",
        "subtitle": "hậu ngọt, ít đắng, vị chua dâu",
        "title": "REVO Đậm Đà",
        "link": "CHI TIẾT",
    },
    {
        "_id": "12345673",
        "index": 7,
        "price": "70.000",
        "picture": "https://i.postimg.cc/BvFwJfx9/slider-element-2.png",
        "subtitle": "hậu ngọt, ít đắng, vị chua dâu",
        "title": "REVO Đậm Đà",
        "link": "CHI TIẾT",
    },
    {
        "_id": "12345674",
        "index": 8,
        "price": "70.000",
        "picture": "https://i.postimg.cc/LXG8NSkg/slider-element-1.png",
        "subtitle": "hậu ngọt, ít đắng, vị chua dâu",
        "title": "REVO Đậm Đà",
        "link": "CHI TIẾT",
    },
    {
        "_id": "12345675",
        "index": 9,
        "price": "70.000",
        "picture": "https://i.postimg.cc/BvFwJfx9/slider-element-2.png",
        "subtitle": "hậu ngọt, ít đắng, vị chua dâu",
        "title": "REVO Đậm Đà",
        "link": "CHI TIẾT",
    },
    {
        "_id": "12345676",
        "index": 10,
        "price": "70.000",
        "picture": "https://i.postimg.cc/mDRVRzLC/slider-element-3.png",
        "subtitle": "hậu ngọt, ít đắng, vị chua dâu",
        "title": "REVO Đậm Đà",
        "link": "CHI TIẾT",
    },
    {
        "_id": "12345677",
        "index": 11,
        "price": "70.000",
        "picture": "https://i.postimg.cc/BvFwJfx9/slider-element-2.png",
        "subtitle": "hậu ngọt, ít đắng, vị chua dâu",
        "title": "REVO Đậm Đà",
        "link": "CHI TIẾT",
    },
    {
        "_id": "12345678",
        "index": 12,
        "price": "70.000",
        "picture": "https://i.postimg.cc/LXG8NSkg/slider-element-1.png",
        "subtitle": "hậu ngọt, ít đắng, vị chua dâu",
        "title": "REVO Đậm Đà",
        "link": "CHI TIẾT",
    },
    {
        "_id": "12345679",
        "index": 13,
        "price": "70.000",
        "picture": "https://i.postimg.cc/BvFwJfx9/slider-element-2.png",
        "subtitle": "hậu ngọt, ít đắng, vị chua dâu",
        "title": "REVO Đậm Đà",
        "link": "CHI TIẾT",
    },
    {
        "_id": "123456710",
        "index": 14,
        "price": "70.000",
        "picture": "https://i.postimg.cc/mDRVRzLC/slider-element-3.png",
        "subtitle": "hậu ngọt, ít đắng, vị chua dâu",
        "title": "REVO Đậm Đà",
        "link": "CHI TIẾT",
    },
    ]
}
